#!/usr/bin/env python3
"""Check a listing pull request before it can be merged automatically.

A listing pull request adds or updates exactly one community entry in
index.json (and regenerates README.md). This script checks the entry, the
creator's repository at the entry's pinned commit, and the module's code in
that commit's archive. The module's code is read as data: its manifest is
parsed, never imported, and nothing in the archive is run.

The outcome is one of:
  pass        every check passed; the merge workflow may merge it
  fail        something must change; the comment says what
  flag        checks passed, but the code does something the listing does not
              declare, so a maintainer reviews it first
  maintainer  opened by a maintainer; reviewed by hand, never merged by a bot

In CI, `check_submission.py <result.json>` reads the pull request from the
GitHub event, writes the outcome and its comment to <result.json>, and exits 1
on fail. Every error ends as fail, never as pass.
"""
from __future__ import annotations

import ast
import hashlib
import importlib.util
import io
import json
import os
import pathlib
import re
import stat
import subprocess
import sys
import tempfile
import zipfile
from dataclasses import dataclass, field

from gen_readme import regenerate
from github_api import ApiError, GitHub, NotFound, TooLarge
from listing import LISTING_FILES, MAINTAINER_ROLES
from scan_module import KINDS, scan_folder
from validate_index import check as validate

ROOT = pathlib.Path(__file__).resolve().parents[1]
MB = 1024 * 1024
# The same caps Celerp applies when it installs a module (celerp/modules/importer.py).
MAX_ARCHIVE_BYTES = 50 * MB
MAX_UNPACKED_BYTES = 200 * MB
ARCHIVE_CAP_TEXT = "50 MB"
UNPACKED_CAP_TEXT = "200 MB"
# A file name only Celerp itself may write into an installed module.
RESERVED_FILES = (".celerp-premium",)
REPO_URL = re.compile(r"https://github\.com/([A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?)/"
                      r"([A-Za-z0-9._-]+)")
# The module template's lint rules, at a fixed commit, with the file's sha256.
TEMPLATE_REPO = "celerp/celerp-module-template"
TEMPLATE_COMMIT = "f863c419441a527e291503d50c53cbd126d13454"
TEMPLATE_LINT_SHA256 = "8ec8d1216b34b896a5cff7215112c6234ce61912eba15805fac979816fc62d1b"
NO_NETWORK = re.compile(r"^\s*(none|no network|n/?a)\b", re.I)
LOOKALIKE = str.maketrans("013457", "oleast")


@dataclass
class Result:
    status: str
    problems: list[str] = field(default_factory=list)
    flags: list[str] = field(default_factory=list)
    entry_id: str | None = None


class _Stop(Exception):
    """A problem that makes the remaining checks meaningless."""


def _q(value: object) -> str:
    """Untrusted text shown inline in a comment."""
    text = " ".join(str(value).split()).replace("`", "'")
    return f"`{text[:200]}`"


def _norm(text: str) -> str:
    return re.sub(r"[^a-z0-9]", "", str(text).lower().translate(LOOKALIKE))


def _owner_of(repo: str) -> str | None:
    m = REPO_URL.fullmatch(repo or "")
    return m.group(1) if m else None


# ── the listing itself ───────────────────────────────────────────────────────

def _scope_problems(changed: list[str]) -> list[str]:
    problems = []
    others = sorted(set(changed) - set(LISTING_FILES))
    if others:
        problems.append(
            f"This pull request changes {', '.join(_q(p) for p in others)}. A listing pull "
            "request may change only index.json, plus README.md as regenerated by "
            "scripts/gen_readme.py. Take the other changes out of this pull request.")
    if "index.json" not in changed:
        problems.append("This pull request does not change index.json. Add or update your "
                        "module's entry in index.json.")
    return problems


def _changed_entry(base: dict, head: dict) -> tuple[dict, dict | None, list[str]]:
    before = {m["id"]: m for m in base["modules"]}
    after = {m["id"]: m for m in head["modules"]}
    problems = [f"The entry {_q(mid)} was removed. A listing pull request may not remove "
                "entries; to take a listing down, open an issue and a maintainer will do it."
                for mid in sorted(set(before) - set(after))]
    touched = [mid for mid, m in after.items() if before.get(mid) != m]
    if len(touched) != 1:
        problems.append(
            "A listing pull request must add or update exactly one entry in index.json; "
            f"this one changes {len(touched)}"
            + (f" ({', '.join(_q(t) for t in touched)})" if touched else "")
            + ". Open one pull request per module.")
        raise _Stop(problems)
    mid = touched[0]
    entry, old = after[mid], before.get(mid)
    if entry["tier"] != "community" or (old and old["tier"] != "community"):
        problems.append(f"{_q(mid)} is not a community listing. Pull requests may add or "
                        "update community listings only: set tier to \"community\".")
        raise _Stop(problems)
    return entry, old, problems


def _ownership_problems(entry: dict, old: dict | None, author: str) -> list[str]:
    owner = _owner_of(entry["repo"])
    if owner is None:
        raise _Stop([f"repo is {_q(entry['repo'])}. It must be the address of a public GitHub "
                     "repository, exactly https://github.com/<owner>/<repository> with nothing "
                     "after the repository name."])
    problems = []
    if owner.lower() != author.lower():
        problems.append(
            f"This pull request was opened by {_q(author)}, but the repository belongs to "
            f"{_q(owner)}. Open the pull request from the GitHub account that owns the "
            "repository.")
    if old is not None:
        old_owner = _owner_of(old.get("repo", "")) or ""
        if old_owner.lower() != author.lower():
            problems.append(f"{_q(old['id'])} is listed by {_q(old_owner)}. Only that account "
                            "can update it; choose a new id for your own module.")
        elif old.get("commit") == entry.get("commit"):
            problems.append(
                f"{_q(entry['id'])} is already listed at commit {_q(entry['commit'])}. Every "
                "update must point commit at a new commit of your repository.")
    return problems


def _celerp_name_problems(labels: dict[str, str]) -> list[str]:
    return [f"The {label} {_q(value)} contains Celerp or a lookalike. Only Celerp's own "
            "modules may use that name; choose your own."
            for label, value in labels.items() if "celerp" in _norm(value)]


def _taken_name_problems(entry: dict, index: dict) -> list[str]:
    problems = []
    mid, name = entry["id"], entry["name"]
    for other in index["modules"]:
        if other["id"] == mid:
            continue
        if other["tier"] == "official":
            short = other["id"].removeprefix("celerp-")
            if {_norm(mid), _norm(name)} & {_norm(short), _norm(other["name"])}:
                problems.append(
                    f"The id {_q(mid)} or name {_q(name)} matches the official module "
                    f"{_q(other['name'])} ({_q(other['id'])}). Choose a name of your own.")
        elif _norm(name) == _norm(other["name"]) or _norm(mid) == _norm(other["id"]):
            problems.append(f"The name {_q(name)} is too close to the listed module "
                            f"{_q(other['name'])} ({_q(other['id'])}). Choose another.")
    return problems


# ── the creator's repository ─────────────────────────────────────────────────

def _repo_problems(entry: dict, gh) -> tuple[str, str, list[str]]:
    owner, name = REPO_URL.fullmatch(entry["repo"]).groups()
    sha = entry["commit"]
    try:
        info = gh.get(f"/repos/{owner}/{name}")
    except NotFound:
        raise _Stop([f"No public GitHub repository was found at {_q(entry['repo'])}. The "
                     "repository must exist and be public."]) from None
    if info.get("private") or info.get("visibility", "public") != "public":
        raise _Stop([f"{_q(entry['repo'])} is private. The repository must be public."])
    if str(info.get("full_name", "")).lower() != f"{owner}/{name}".lower():
        raise _Stop([f"repo {_q(entry['repo'])} now points to {_q(info.get('full_name'))}. "
                     "Set repo to the repository's current address."])
    problems = []
    default = info.get("default_branch") or "main"
    try:
        compare = gh.get(f"/repos/{owner}/{name}/compare/{default}...{sha}")
        on_default = compare.get("status") in ("identical", "behind")
    except NotFound:
        on_default = False
    if not on_default:
        problems.append(f"commit {_q(sha)} is not on the repository's default branch "
                        f"{_q(default)}. Push the commit to {_q(default)} and use its full "
                        "40-character id.")
    try:
        spdx = (gh.get(f"/repos/{owner}/{name}/license?ref={sha}").get("license") or {}) \
            .get("spdx_id")
    except NotFound:
        problems.append("The repository has no license file at this commit. Add a LICENSE "
                        "file that matches the license in your entry.")
    else:
        if spdx and spdx != "NOASSERTION" and spdx.lower() != entry["license"].lower():
            problems.append(f"The repository's license is {_q(spdx)} but the entry says "
                            f"{_q(entry['license'])}. Make them the same.")
    return owner, name, problems


def _is_manifest(data: bytes) -> bool:
    try:
        tree = ast.parse(data.decode("utf-8"))
    except (UnicodeDecodeError, SyntaxError, ValueError):
        return False
    return _manifest_node(tree) is not None


def _manifest_node(tree: ast.AST):
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == "PLUGIN_MANIFEST" for t in node.targets):
            return node
    return None


def _manifest(data: bytes) -> dict | None:
    node = _manifest_node(ast.parse(data.decode("utf-8")))
    try:
        value = ast.literal_eval(node.value)
    except (ValueError, TypeError, SyntaxError, MemoryError, RecursionError):
        return None
    return value if isinstance(value, dict) else None


def _module_files(data: bytes, mid: str) -> dict[str, bytes]:
    """The module folder's files, located the way Celerp locates them on install."""
    try:
        zf = zipfile.ZipFile(io.BytesIO(data))
    except zipfile.BadZipFile:
        raise _Stop(["The repository archive at this commit could not be read."]) from None
    with zf:
        files: dict[str, bytes] = {}
        unpacked = 0
        problems = []
        for info in zf.infolist():
            parts = info.filename.split("/", 1)
            rel = parts[1] if len(parts) == 2 else ""
            if not rel or rel.endswith("/"):
                continue
            path = pathlib.PurePosixPath(rel)
            if path.is_absolute() or ".." in path.parts or "\\" in rel:
                problems.append(f"{_q(rel)} has a path Celerp will not unpack. Rename it.")
                continue
            if stat.S_ISLNK((info.external_attr >> 16) & 0xFFFF):
                problems.append(f"{_q(rel)} is a symbolic link. A module may contain only "
                                "regular files.")
                continue
            if path.name in RESERVED_FILES:
                problems.append(f"{_q(rel)} is a file name Celerp reserves. Remove it.")
                continue
            unpacked += info.file_size
            if unpacked > MAX_UNPACKED_BYTES:
                raise _Stop([f"The repository unpacks to more than {UNPACKED_CAP_TEXT}, the "
                             "most Celerp installs. Remove large files from the repository."])
            files[rel] = zf.read(info)
        if problems:
            raise _Stop(problems)
    if _is_manifest(files.get("__init__.py", b"")):
        return files
    roots = sorted(str(pathlib.PurePosixPath(p).parent) for p, b in files.items()
                   if pathlib.PurePosixPath(p).name == "__init__.py" and _is_manifest(b))
    if roots != [mid]:
        raise _Stop([f"The repository must hold exactly one module, in a folder named "
                     f"{_q(mid)} at its top level with an __init__.py that has "
                     f"PLUGIN_MANIFEST; found {', '.join(_q(r) for r in roots) or 'none'}."])
    return {p[len(mid) + 1:]: b for p, b in files.items() if p.startswith(mid + "/")}


def _module_problems(entry: dict, files: dict[str, bytes], lint) -> tuple[dict, list[str]]:
    manifest = _manifest(files["__init__.py"])
    if manifest is None:
        raise _Stop(["PLUGIN_MANIFEST in __init__.py must be a dict of plain values."])
    problems = []
    if manifest.get("name") != entry["id"]:
        problems.append(f"The manifest name is {_q(manifest.get('name'))} but the entry id is "
                        f"{_q(entry['id'])}. They must be the same.")
    if manifest.get("license") != entry["license"]:
        problems.append(f"The manifest license is {_q(manifest.get('license'))} but the entry "
                        f"says {_q(entry['license'])}. They must be the same.")
    with tempfile.TemporaryDirectory() as tmp:
        folder = pathlib.Path(tmp) / entry["id"]
        for rel, data in files.items():
            dest = folder / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(data)
        problems += [f"Template lint: {p.replace(str(folder), entry['id'])}" for p in lint(folder)]
    return manifest, problems


def _flags(entry: dict, files: dict[str, bytes]) -> list[str]:
    declares_network = not NO_NETWORK.match(entry["network_calls"])
    flags = []
    for f in sorted(scan_folder(files), key=lambda f: (f.path, f.line, f.kind)):
        if f.kind == "network" and declares_network:
            continue
        if f.kind == "network":
            why = "network_calls in your entry says it makes none"
        elif f.kind == "files":
            why = "a module keeps its files in Celerp's data folder (settings.data_dir)"
        else:
            why = "a maintainer reviews this in every module"
        flags.append(f"{_q(f.path)} line {f.line} {KINDS[f.kind]} ({f.detail}); {why}.")
    return flags


# ── the whole review ─────────────────────────────────────────────────────────

def review(*, base: dict, head: dict, changed: list[str], author: str, association: str,
           gh, lint) -> Result:
    """Check a listing pull request. base/head map file names to their text."""
    if association in MAINTAINER_ROLES:
        return Result("maintainer")
    problems = _scope_problems(changed)
    entry_id = None
    flags: list[str] = []
    try:
        try:
            head_index = json.loads(head["index.json"])
            base_index = json.loads(base["index.json"])
        except ValueError as exc:
            raise _Stop([f"index.json is not valid JSON: {exc}"]) from None
        schema = json.loads((ROOT / "schema" / "index.schema.json").read_text(encoding="utf-8"))
        invalid = validate(head_index, schema)
        if invalid:
            raise _Stop([f"index.json: {p}" for p in invalid])
        try:
            readme_ok = regenerate(base["README.md"], head_index) == head["README.md"]
        except ValueError:
            readme_ok = False
        if not readme_ok:
            problems.append("README.md does not match what scripts/gen_readme.py builds from "
                            "index.json. Do not edit README.md by hand: run "
                            "`python3 scripts/gen_readme.py` and commit the result.")
        entry, old, found = _changed_entry(base_index, head_index)
        entry_id = entry["id"]
        problems += found
        problems += _ownership_problems(entry, old, author)
        problems += _celerp_name_problems({"id": entry["id"], "name": entry["name"]})
        problems += _taken_name_problems(entry, head_index)
        owner, name, found = _repo_problems(entry, gh)
        problems += found
        try:
            archive = gh.download(f"https://codeload.github.com/{owner}/{name}/zip/"
                                  f"{entry['commit']}", MAX_ARCHIVE_BYTES)
        except TooLarge:
            raise _Stop([f"The repository archive at this commit is larger than "
                         f"{ARCHIVE_CAP_TEXT}, the most Celerp installs. Remove large files "
                         "from the repository."]) from None
        except NotFound:
            raise _Stop([f"The archive of commit {_q(entry['commit'])} could not be "
                         "downloaded. Check that the commit exists and is pushed."]) from None
        files = _module_files(archive, entry_id)
        manifest, found = _module_problems(entry, files, lint)
        problems += found
        problems += _celerp_name_problems(
            {"display_name in the manifest": str(manifest.get("display_name", ""))})
        flags = _flags(entry, files)
    except _Stop as stop:
        problems += stop.args[0]
    except ApiError as exc:
        problems.append(f"The check could not finish because GitHub did not answer as "
                        f"expected ({_q(exc)}). Push a new commit (an empty one is fine) to "
                        "run it again.")
    if problems:
        return Result("fail", problems, [], entry_id)
    return Result("flag" if flags else "pass", [], flags, entry_id)


def _bullets(items: list[str]) -> str:
    return "\n".join("- " + i.replace("@", "@\u200b").replace("\u2014", "-") for i in items)


def comment(result: Result) -> str:
    if result.status == "fail":
        return ("## Listing check: changes needed\n\n"
                "This listing cannot be merged yet. Fix each item below in your repository or "
                "your fork of this one, then push a new commit to this pull request. The check "
                "runs again by itself.\n\n" + _bullets(result.problems) + "\n")
    if result.status == "flag":
        return ("## Listing check: waiting for the maintainer\n\n"
                "Every required check passed, but the module's code does the things below, "
                "which its entry does not declare or which a maintainer always reviews. A "
                "maintainer will review it before it is listed. If your entry should declare "
                "something (for example a network call in network_calls), update it and push "
                "a new commit; otherwise nothing is needed from you.\n\n"
                + _bullets(result.flags) + "\n")
    if result.status == "maintainer":
        return ("## Listing check: maintainer pull request\n\n"
                "Opened by a maintainer, so it is reviewed and merged by hand.\n")
    return ("## Listing check: passed\n\n"
            "Every check passed. This pull request is merged automatically, and the module "
            "appears in Celerp's catalog on its next refresh.\n")


# ── CI entry point ───────────────────────────────────────────────────────────

def _git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, check=True, capture_output=True,
                          text=True).stdout


def template_lint(gh):
    """The module template's `lint(folder)`, at its pinned commit."""
    url = (f"https://raw.githubusercontent.com/{TEMPLATE_REPO}/{TEMPLATE_COMMIT}/lint.py")
    source = gh.download(url, MB)
    if hashlib.sha256(source).hexdigest() != TEMPLATE_LINT_SHA256:
        raise ApiError("the template lint file did not match its pinned hash")
    path = pathlib.Path(tempfile.mkdtemp()) / "template_lint.py"
    path.write_bytes(source)
    spec = importlib.util.spec_from_file_location("template_lint", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.lint


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: check_submission.py <result.json>")
        return 2
    event = json.loads(pathlib.Path(os.environ["GITHUB_EVENT_PATH"]).read_text())
    pr = event["pull_request"]
    base_sha = _git("rev-parse", "HEAD^1").strip()
    try:
        changed = _git("diff", "--name-only", "--no-renames", "HEAD^1", "HEAD").split()
        base = {f: _git("show", f"HEAD^1:{f}") for f in LISTING_FILES}
        head = {f: (ROOT / f).read_text(encoding="utf-8") for f in LISTING_FILES}
        gh = GitHub()
        result = review(base=base, head=head, changed=changed, author=pr["user"]["login"],
                        association=pr.get("author_association", ""), gh=gh,
                        lint=template_lint(gh))
    except Exception as exc:  # fail closed: any error is a failed check
        result = Result("fail", [f"The check could not finish ({_q(type(exc).__name__)}). "
                                 "Push a new commit (an empty one is fine) to run it again."])
    text = comment(result)
    pathlib.Path(sys.argv[1]).write_text(json.dumps({
        "pr": pr["number"], "head_sha": pr["head"]["sha"], "base_sha": base_sha,
        "status": result.status, "comment": text}))
    print(text)
    return 1 if result.status == "fail" else 0


if __name__ == "__main__":
    sys.exit(main())
